src/Entity/ItemBudget.php
<?php

namespace App\Entity;

use App\Repository\ItemBudgetRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Uid\Uuid;

/**
 * @ORM\Entity(repositoryClass=ItemBudgetRepository::class)
 */
class ItemBudget
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="doctrine.uuid_generator")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Budget::class, inversedBy="itemBudgets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $budget;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $costo;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $unidad_costo;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $cantidad_costo;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="itemBudgets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $producto;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $excendentes;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $excedentes_costo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $observacion;

    /**
     * @var string|null
     *
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */

    protected $createdBy;

    /**
     * @var string|null
     *
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    protected $updatedBy;

    /**
     * @var string|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="content_changed_by", referencedColumnName="id")
     * @Gedmo\Blameable(on="change", field={"title", "descripcion", "isAvailable", "identifier", "isForSale"})
     */
    protected $contentChangedBy;

    public function __toString()
    {
     return $this->producto->title;
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getBudget(): ?Budget
    {
        return $this->budget;
    }

    public function setBudget(?Budget $budget): self
    {
        $this->budget = $budget;

        return $this;
    }

    public function getCosto(): ?float
    {
        return $this->costo;
    }

    public function setCosto(?float $costo): self
    {
        $this->costo = $costo;

        return $this;
    }

    public function getUnidadCosto(): ?string
    {
        return $this->unidad_costo;
    }

    public function setUnidadCosto(?string $unidad_costo): self
    {
        $this->unidad_costo = $unidad_costo;

        return $this;
    }

    public function getCantidadCosto(): ?float
    {
        return $this->cantidad_costo;
    }

    public function setCantidadCosto(?float $cantidad_costo): self
    {
        $this->cantidad_costo = $cantidad_costo;

        return $this;
    }

    public function getProducto(): ?Product
    {
        return $this->producto;
    }

    public function setProducto(?Product $producto): self
    {
        $this->producto = $producto;

        return $this;
    }

    public function getExcendentes(): ?string
    {
        return $this->excendentes;
    }

    public function setExcendentes(?string $excendentes): self
    {
        $this->excendentes = $excendentes;

        return $this;
    }

    public function getExcedentesCosto(): ?float
    {
        return $this->excedentes_costo;
    }

    public function setExcedentesCosto(?float $excedentes_costo): self
    {
        $this->excedentes_costo = $excedentes_costo;

        return $this;
    }

    public function getObservacion(): ?string
    {
        return $this->observacion;
    }

    public function setObservacion(?string $observacion): self
    {
        $this->observacion = $observacion;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCreatedBy(): ?string
    {
        return $this->createdBy;
    }

    /**
     * @return string|null
     */
    public function getUpdatedBy(): ?string
    {
        return $this->updatedBy;
    }

    /**
     * @return string|null
     */
    public function getContentChangedBy(): ?string
    {
        return $this->contentChangedBy;
    }
}

src/Form/ItemBudgetType.php
<?php

namespace App\Form;

use App\Entity\ItemBudget;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ItemBudgetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('costo')
            ->add('unidad_costo')
            ->add('cantidad_costo')
            ->add('excendentes')
            ->add('excedentes_costo')
            ->add('observacion')
            ->add('budget')
            ->add('producto')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ItemBudget::class,
        ]);
    }
}

src/Controller/ItemBudgetController.php
<?php

namespace App\Controller;

use App\Entity\ItemBudget;
use App\Form\ItemBudgetType;
use App\Repository\ItemBudgetRepository;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ventas/item_presupuesto")
 */
class ItemBudgetController extends AbstractController
{
    /**
     * @Route("/", name="app_item_budget_index", methods={"GET"})
     */
    public function index(ItemBudgetRepository $itemBudgetRepository): Response
    {
        return $this->render('item_budget/index.html.twig', [
            'item_budgets' => $itemBudgetRepository->findAll(),
        ]);
    }

    /**
     * @Route("/prebudget", name="app_item_budget_prebudget", methods={"GET"})
     * @param ItemBudgetRepository $itemBudgetRepository
     * @param ProductRepository $productRepository
     * @return Response
     */
    public function preBudget(ItemBudgetRepository $itemBudgetRepository, ProductRepository $productRepository): Response
    {

        return $this->render('item_budget/list-pre-budget.html.twig', [
            'item_budgets' => $itemBudgetRepository->findAll(),
            'products' => $productRepository->findBy(['isAvailable' => true, 'isForSale' => true])
        ]);
    }

    /**
     * @Route("/new", name="app_item_budget_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ItemBudgetRepository $itemBudgetRepository): Response
    {
        $itemBudget = new ItemBudget();
        $form = $this->createForm(ItemBudgetType::class, $itemBudget);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $itemBudgetRepository->add($itemBudget, true);

            return $this->redirectToRoute('app_item_budget_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('item_budget/new.html.twig', [
            'item_budget' => $itemBudget,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_item_budget_show", methods={"GET"})
     */
    public function show(ItemBudget $itemBudget): Response
    {
        return $this->render('item_budget/show.html.twig', [
            'item_budget' => $itemBudget,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_item_budget_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ItemBudget $itemBudget, ItemBudgetRepository $itemBudgetRepository): Response
    {
        $form = $this->createForm(ItemBudgetType::class, $itemBudget);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $itemBudgetRepository->add($itemBudget, true);

            return $this->redirectToRoute('app_item_budget_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('item_budget/edit.html.twig', [
            'item_budget' => $itemBudget,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_item_budget_delete", methods={"POST"})
     */
    public function delete(Request $request, ItemBudget $itemBudget, ItemBudgetRepository $itemBudgetRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$itemBudget->getId(), $request->request->get('_token'))) {
            $itemBudgetRepository->remove($itemBudget, true);
        }

        return $this->redirectToRoute('app_item_budget_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/item_budget/_delete_form.html.twig
<form method="post" action="{{ path('app_item_budget_delete', {'id': item_budget.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ item_budget.id) }}">
    <button class="btn">Borrar</button>
</form>

templates/item_budget/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/item_budget/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item presupuesto editar{% endblock %}

{% block body %}
    <h1>Item presupuesto editar</h1>

    {{ include('item_budget/_form.html.twig', {'button_label': 'Actualizar'}) }}

    <a href="{{ path('app_item_budget_index') }}">Listado</a>

    {{ include('item_budget/_delete_form.html.twig') }}
{% endblock %}

templates/item_budget/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item presupuesto Listado{% endblock %}

{% block body %}
    <h1>Item presupuesto Listado</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Costo</th>
                <th>Unidad medida</th>
                <th>Cantidad</th>
                <th>Excedentes</th>
                <th>Excedentes costo</th>
                <th>Observación</th>
                <th>Creado</th>
                <th>Actualizado</th>
                <th><i class="fa fa-cogs"></i> </th>
            </tr>
        </thead>
        <tbody>
        {% for item_budget in item_budgets %}
            <tr>
                <td>{{ item_budget.id }}</td>
                <td>{{ item_budget.costo }}</td>
                <td>{{ item_budget.unidadCosto }}</td>
                <td>{{ item_budget.cantidadCosto }}</td>
                <td>{{ item_budget.excendentes }}</td>
                <td>{{ item_budget.excedentesCosto }}</td>
                <td>{{ item_budget.observacion }}</td>
                <td>{{ item_budget.createdAt ? item_budget.createdAt|date('d-m-Y H:i:s') : '' }}</td>
                <td>{{ item_budget.updatedAt ? item_budget.updatedAt|date('d-m-Y H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_item_budget_show', {'id': item_budget.id}) }}">Ver</a>
                    <a href="{{ path('app_item_budget_edit', {'id': item_budget.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">No se encontraron Items</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{#    <a href="{{ path('app_item_budget_new') }}">Create new</a>#}
{% endblock %}

templates/item_budget/list-pre-budget.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item presupuesto Listado{% endblock %}

{% block body %}
    <h1>Item presupuesto Listado</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Costo</th>
            <th>Unidad medida</th>
            <th>Cantidad</th>
            <th>Excedentes</th>
            <th>Excedentes costo</th>
            <th>Observación</th>
            <th>Creado</th>
            <th>Actualizado</th>
            <th><i class="fa fa-cogs"></i></th>
        </tr>
        </thead>
        <tbody>
        {% for item_budget in item_budgets %}
            <tr>
                <td>{{ item_budget.id }}</td>
                <td>{{ item_budget.costo }}</td>
                <td>{{ item_budget.unidadCosto }}</td>
                <td>{{ item_budget.cantidadCosto }}</td>
                <td>{{ item_budget.excendentes }}</td>
                <td>{{ item_budget.excedentesCosto }}</td>
                <td>{{ item_budget.observacion }}</td>
                <td>{{ item_budget.createdAt ? item_budget.createdAt|date('d-m-Y H:i:s') : '' }}</td>
                <td>{{ item_budget.updatedAt ? item_budget.updatedAt|date('d-m-Y H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_item_budget_show', {'id': item_budget.id}) }}">Ver</a>
                    <a href="{{ path('app_item_budget_edit', {'id': item_budget.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">No se encontraron Items</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {{ dump(products) }}

    {#    <a href="{{ path('app_item_budget_new') }}">Create new</a> #}
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        window.products= {{ products|json }};
    </script>
{% endblock %}

templates/item_budget/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item presupuesto nuevo{% endblock %}

{% block body %}
    <h1>Item presupuesto nuevo</h1>

    {{ include('item_budget/_form.html.twig') }}

    <a href="{{ path('app_item_budget_index') }}">Listado</a>
{% endblock %}

templates/item_budget/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Item presupuesto ver{% endblock %}

{% block body %}
    <h1>Item presupuesto ver</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ item_budget.id }}</td>
            </tr>
            <tr>
                <th>Costo</th>
                <td>{{ item_budget.costo }}</td>
            </tr>
            <tr>
                <th>Unidad medida</th>
                <td>{{ item_budget.unidadCosto }}</td>
            </tr>
            <tr>
                <th>Cantidad</th>
                <td>{{ item_budget.cantidadCosto }}</td>
            </tr>
            <tr>
                <th>Excedentes</th>
                <td>{{ item_budget.excendentes }}</td>
            </tr>
            <tr>
                <th>Excedentes costo</th>
                <td>{{ item_budget.excedentesCosto }}</td>
            </tr>
            <tr>
                <th>Observación</th>
                <td>{{ item_budget.observacion }}</td>
            </tr>
            <tr>
                <th>Creado</th>
                <td>{{ item_budget.createdAt ? item_budget.createdAt|date('d-m-Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Actualizado</th>
                <td>{{ item_budget.updatedAt ? item_budget.updatedAt|date('d-m-Y H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_item_budget_index') }}">Listado</a>

    <a href="{{ path('app_item_budget_edit', {'id': item_budget.id}) }}">Editar</a>

    {{ include('item_budget/_delete_form.html.twig') }}
{% endblock %}