src/Entity/Budget.php
<?php

namespace App\Entity;

use App\Repository\BudgetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\GeneratedValue;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Uid\Uuid;

/**
 * @ORM\Entity(repositoryClass=BudgetRepository::class)
 */
class Budget
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="doctrine.uuid_generator")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Cliente::class, inversedBy="budgets")
     */
    private $cliente;

    /**
     * @ORM\ManyToMany(targetEntity=Product::class, inversedBy="budgets")
     */
    private $productos;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $aclaraciones;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $cliente_confirma;

    /**
     * @var string|null
     *
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */

    protected $createdBy;

    /**
     * @var string|null
     *
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    protected $updatedBy;

    /**
     * @var string|null
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="content_changed_by", referencedColumnName="id")
     * @Gedmo\Blameable(on="change", field={"aclaraciones", "cliente_confirma"})
     */
    protected $contentChangedBy;

    /**
     * @ORM\OneToMany(targetEntity=ItemBudget::class, mappedBy="budget")
     */
    private $itemBudgets;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $total;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $nro_budget;

    /**
     * @ORM\OneToOne(targetEntity=NroFactura::class, mappedBy="budget", cascade={"persist", "remove"})
     */
    private $nroFactura;

    public function __construct()
    {
        $this->productos = new ArrayCollection();
        $this->itemBudgets = new ArrayCollection();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getCliente(): ?Cliente
    {
        return $this->cliente;
    }

    public function setCliente(?Cliente $cliente): self
    {
        $this->cliente = $cliente;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProductos(): Collection
    {
        return $this->productos;
    }

    public function addProducto(Product $producto): self
    {
        if (!$this->productos->contains($producto)) {
            $this->productos[] = $producto;
        }

        return $this;
    }

    public function removeProducto(Product $producto): self
    {
        $this->productos->removeElement($producto);

        return $this;
    }

    public function getAclaraciones(): ?string
    {
        return $this->aclaraciones;
    }

    public function setAclaraciones(?string $aclaraciones): self
    {
        $this->aclaraciones = $aclaraciones;

        return $this;
    }

    public function getClienteConfirma(): ?string
    {
        return $this->cliente_confirma;
    }

    public function setClienteConfirma(?string $cliente_confirma): self
    {
        $this->cliente_confirma = $cliente_confirma;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCreatedBy(): ?string
    {
        return $this->createdBy;
    }

    /**
     * @return string|null
     */
    public function getUpdatedBy(): ?string
    {
        return $this->updatedBy;
    }

    /**
     * @return string|null
     */
    public function getContentChangedBy(): ?string
    {
        return $this->contentChangedBy;
    }

    /**
     * @return Collection<int, ItemBudget>
     */
    public function getItemBudgets(): Collection
    {
        return $this->itemBudgets;
    }

    public function addItemBudget(ItemBudget $itemBudget): self
    {
        if (!$this->itemBudgets->contains($itemBudget)) {
            $this->itemBudgets[] = $itemBudget;
            $itemBudget->setBudget($this);
        }

        return $this;
    }

    public function removeItemBudget(ItemBudget $itemBudget): self
    {
        if ($this->itemBudgets->removeElement($itemBudget)) {
            // set the owning side to null (unless already changed)
            if ($itemBudget->getBudget() === $this) {
                $itemBudget->setBudget(null);
            }
        }

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(?float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getNroBudget(): ?int
    {
        return $this->nro_budget;
    }

    public function setNroBudget(int $nro_budget): self
    {
        $this->nro_budget = $nro_budget;

        return $this;
    }

    public function getNroFactura(): ?NroFactura
    {
        return $this->nroFactura;
    }

    public function setNroFactura(?NroFactura $nroFactura): self
    {
        // unset the owning side of the relation if necessary
        if ($nroFactura === null && $this->nroFactura !== null) {
            $this->nroFactura->setBudget(null);
        }

        // set the owning side of the relation if necessary
        if ($nroFactura !== null && $nroFactura->getBudget() !== $this) {
            $nroFactura->setBudget($this);
        }

        $this->nroFactura = $nroFactura;

        return $this;
    }
}

src/Entity/Cliente.php
<?php

namespace App\Entity;

use App\Repository\ClienteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Uid\Uuid;

/**
 * @ORM\Entity(repositoryClass=ClienteRepository::class)
 */
class Cliente
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="doctrine.uuid_generator")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $razon_social;

    /**
     * @ORM\Column(type="string", length=510, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $emial;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cuit;

    /**
     * @var string|null
     *
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */

    protected $createdBy;

    /**
     * @var string|null
     *
     * @Gedmo\Blameable(on="update")
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    protected $updatedBy;

    /**
     * @var string|null
     *
     *@ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(name="content_changed_by", referencedColumnName="id")
     * @Gedmo\Blameable(on="change", field={"razon_social", "address", "phone", "emial", "cuit"})
     */
    protected $contentChangedBy;

    /**
     * @ORM\OneToMany(targetEntity=Budget::class, mappedBy="cliente")
     */
    private $budgets;

    public function __construct()
    {
        $this->budgets = new ArrayCollection();
    }

    public function __toString()
    {
     return $this->razon_social;
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getRazonSocial(): ?string
    {
        return $this->razon_social;
    }

    public function setRazonSocial(string $razon_social): self
    {
        $this->razon_social = $razon_social;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmial(): ?string
    {
        return $this->emial;
    }

    public function setEmial(?string $emial): self
    {
        $this->emial = $emial;

        return $this;
    }

    public function getCuit(): ?string
    {
        return $this->cuit;
    }

    public function setCuit(?string $cuit): self
    {
        $this->cuit = $cuit;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCreatedBy(): ?string
    {
        return $this->createdBy;
    }

    /**
     * @return string|null
     */
    public function getUpdatedBy(): ?string
    {
        return $this->updatedBy;
    }

    /**
     * @return string|null
     */
    public function getContentChangedBy(): ?string
    {
        return $this->contentChangedBy;
    }

    /**
     * @return Collection<int, Budget>
     */
    public function getBudgets(): Collection
    {
        return $this->budgets;
    }

    public function addBudget(Budget $budget): self
    {
        if (!$this->budgets->contains($budget)) {
            $this->budgets[] = $budget;
            $budget->setCliente($this);
        }

        return $this;
    }

    public function removeBudget(Budget $budget): self
    {
        if ($this->budgets->removeElement($budget)) {
            // set the owning side to null (unless already changed)
            if ($budget->getCliente() === $this) {
                $budget->setCliente(null);
            }
        }

        return $this;
    }


}

src/Form/BudgetType.php
<?php

namespace App\Form;

use App\Entity\Budget;
use App\Entity\Cliente;
use App\Entity\Product;
use App\Repository\ProductRepository;
use AppBundle\Entity\RepLog;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Choice;

class BudgetType extends AbstractType
{
    private ProductRepository $productRepository;

    public function __construct(ProductRepository $productRepository)
    {
        $this->productRepository = $productRepository;
    }


    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $productosSales = $this->productRepository->getProductsForSales();
        $choices = array();
        foreach ($productosSales as $producto) {
            $choices[$producto->getTitle()] = $producto->getId()->toRfc4122();
        }
        $builder
            ->add('cliente', EntityType::class, [
                'class' => Cliente::class,
                'attr' => [
                    'class' => 'selection2 form-control'
                ]
            ])
            ->add('productos', ChoiceType::class, [
                'choices' => $choices,
                'placeholder' => '¿Que producto desea ingresar?',
                'label' => 'Productos',
                'mapped' => false,
                'attr' => [
                    'class' => 'selection2 form-control col-sm-3',
                ]

            ])
            ->add('aclaraciones', TextareaType::class, [
                'attr' => [
                    'cols' => 50,
                    'rows' => 10
                ]
            ])
            ->add('itemBudgets', CollectionType::class, [
                'prototype' => new ItemBudgetType(),
                'allow_add' => true,
                'allow_delete' => true,
            ])
            ->add('cliente_confirma')
            ->add('total');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Budget::class,
        ]);
    }
}

src/Controller/BudgetController.php
<?php

namespace App\Controller;

use App\Entity\Budget;
use App\Entity\NroFactura;
use App\Form\BudgetType;
use App\Repository\BudgetRepository;
use App\Repository\NroFacturaRepository;
use DateTime;
use Spipu\Html2Pdf\Html2Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ventas/presupuesto")
 */
class BudgetController extends AbstractController
{
    /**
     * @Route("/", name="app_budget_index", methods={"GET"})
     */
    public function index(BudgetRepository $budgetRepository): Response
    {
        return $this->render('budget/index.html.twig', [
            'budgets' => $budgetRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_budget_new", methods={"GET", "POST"})
     */
    public function new(
        Request $request,
        BudgetRepository $budgetRepository,
        NroFacturaRepository $nroFacturaRepository
    ): Response {
        $budget = new Budget();
        $form = $this->createForm(BudgetType::class, $budget);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $nroFactura = new NroFactura();
            $nroFacturaRepository->add($nroFactura, true);
            $budget->setNroBudget($nroFactura->getId());
            $budget->setNroFactura($nroFactura);
            $productos = $form->get('productos')->getData();
            foreach ($productos as $producto) {
                $budget->addProducto($producto);
            }

            $budgetRepository->add($budget, true);

            $nroFactura->setBudget($budget);
            $nroFacturaRepository->add($nroFactura, true);
            if ($this->isGranted('ROLE_SUPERVISOR_VENTAS')) {
                return $this->redirectToRoute('app_budget_index', [], Response::HTTP_SEE_OTHER);
            }

            return $this->redirectToRoute('app_budget_show', ['id' => $budget->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('budget/new.html.twig', [
            'budget' => $budget,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_budget_show", methods={"GET"})
     */
    public function show(Budget $budget): Response
    {
        return $this->render('budget/show.html.twig', [
            'budget' => $budget,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_budget_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Budget $budget, BudgetRepository $budgetRepository): Response
    {
        $form = $this->createForm(BudgetType::class, $budget);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $budgetRepository->add($budget, true);

            return $this->redirectToRoute('app_budget_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('budget/edit.html.twig', [
            'budget' => $budget,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_budget_delete", methods={"POST"})
     */
    public function delete(Request $request, Budget $budget, BudgetRepository $budgetRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$budget->getId(), $request->request->get('_token'))) {
            $budgetRepository->remove($budget, true);
        }

        return $this->redirectToRoute('app_budget_index', [], Response::HTTP_SEE_OTHER);
    }
    
    /**
     * @Route("/getPdf/{budget}", name="app_budget_get_pdf", methods={"GET"})
     */
    public function generarPdf(Request $request, Budget $budget)
    {
        ob_start();
        $html = $this->renderView('budget/pdf.html.twig',[
            'presupuesto' => $budget,
            'actualDate' => new DateTime()
        ]);

        $html2pdf = new Html2Pdf('P', 'A4', 'es', true, 'UTF-8', array('10', '10', '10', '10'));
        $html2pdf->pdf->SetDisplayMode('real');
        $html2pdf->setDefaultFont('helvetica');
        $html2pdf->writeHTML($html);

        $cadena = 'presupuesto'.$budget->getNroBudget().'.pdf';
        $originales = 'ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûýýþÿŔŕ';
        $modificadas = 'aaaaaaaceeeeiiiidnoooooouuuuybsaaaaaaaceeeeiiiidnoooooouuuyybyRr';

        $cadena = utf8_decode($cadena);
        $cadena = strtr($cadena, utf8_decode($originales), $modificadas);
        $cadena = strtoupper($cadena);

        ob_end_clean();

        return new Response($html2pdf->Output(utf8_encode($cadena), 'D'), 200, [
            'Content-Type' => 'application/pdf;charset=UTF-8'
        ]);
    }
}

templates/budget/_delete_form.html.twig
{#<form method="post" action="{{ path('app_budget_delete', {'id': budget.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">#}
{#    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ budget.id) }}">#}
{#    <button class="btn">Delete</button>#}
{#</form>#}

templates/budget/_form.html.twig
{{ form_start(form) }}
<div class="my-2">
    {{ form_widget(form.cliente) }}
</div>
<div class="col-sm-12">
    <div class="col-sm-3">
        Producto
    </div>
    <div class="col-sm-1">
        Unidades
    </div>
    <div class="col-sm-2">
        Costo unitario
    </div>
    <div class="col-sm-2">
        Costo de excedentes
    </div>
    <div class="col-sm-3">
        Observación
    </div>
    <div class="col-sm-1">

    </div>
    <br/>
    <div class="js-item-row">
    <div class="col-sm-3">
        {{ form_widget(form.productos) }}
    </div>

        <div class="col-sm-1">
            <input type="text" class="form-control ">
        </div>
        <div class="col-sm-2">
            <input type="text" class="form-control" readonly>
        </div>
        <div class="col-sm-2">
            <input type="text" class="form-control ">
        </div>
        <div class="col-sm-3">
            <input type="text" class="form-control ">
        </div>
        <div class="col-sm-1">
            <a href="#" class="js-add-item">
                <i class="fa fa-plus-square fa-2x"> </i>
            </a>
        </div>
    </div>
</div>
{{ form_rest(form) }}

<button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/budget/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Presupuesto Editar{% endblock %}

{% block body %}
    <h1>Presupuesto Editar</h1>

    {{ include('budget/_form.html.twig', {'button_label': 'Actualizar'}) }}

    <a href="{{ path('app_budget_index') }}">Listado</a>

{#    {{ include('budget/_delete_form.html.twig') }}#}
{% endblock %}

templates/budget/index.html.twig
{% extends "admin/bars.html.twig" %}

{% block title %}Presupuesto Listado{% endblock %}

{% block contenpage %}
    <h1>Presupuesto Listado</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Aclaraciones</th>
                <th>Cliente confirma</th>
                <th>Total</th>
                <th>Nro Presupuesto </th>
                <th><i class="fab fa-cogs"></i> </th>
            </tr>
        </thead>
        <tbody>
        {% for budget in budgets %}
            <tr>
                <td>{{ budget.id }}</td>
                <td>{{ budget.aclaraciones }}</td>
                <td>{{ budget.clienteConfirma }}</td>
                <td>{{ budget.total }}</td>
                <td>{{ budget.nroBudget }}</td>
                <td>{{ budget.createdAt ? budget.createdAt|date('d-m-Y H:i:s') : '' }}</td>
                <td>{{ budget.updatedAt ? budget.updatedAt|date('d-m-Y H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_budget_show', {'id': budget.id}) }}">Ver</a>
                    <a href="{{ path('app_budget_edit', {'id': budget.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">No se encontraron presupuestos </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_budget_new') }}">Crear nuevo presupuesto </a>
{% endblock %}

templates/budget/new.html.twig
{% extends "admin/bars.html.twig" %}

{% block title %}Crear nuevo presupuesto{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('vendors/select2/dist/css/select2.min.css') }}" rel="stylesheet">
{% endblock %}


{% block contenpage %}
    <h1>Crear nuevo presupuesto</h1>
    <div class="me">
        <a href="{{ path('app_cliente_new') }}" class="btn btn-info btn-sm"> Crear cliente</a>
    </div>

    {{ include('budget/_form.html.twig') }}

    <a href="{{ path('app_budget_index') }}">Listado</a>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('vendors/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('vendors/select2/dist/js/select2.min.js') }}"></script>
    <script src="{{ asset('vendors/select2/dist/js/i18n/es.js') }}"></script>
    <script>
        // import Scripts from "../../public/vendors/bootstrap/site/_includes/scripts.html";
        //
        // export default {
        //     components: {Scripts}
        // }
        $(document).ready(function () {
            $('.selection2').select2({
                placeholder: 'Seleccione por favor',
                language: "es",
                allowClear: true,
                width: '100%',
            });

            const $div = $('.js-item-row');
            $div.find('.js-add-item').on('click', function (e) {
                e.preventDefault()
                console.log('todo ');
                $(this).addClass('text-danger')
                $(this).find('.fa')
                    .removeClass('fa-plus-square')
                    .addClass('fa-spinner')
                    .addClass('fa-spin')
                console.log(e.currentTarget === this);
                // e.target.classname = e.target.classname + ' text-danger';


            });
            $div.find('.js-delete-item').on('click', function (e) {
                e.preventDefault()
                console.log('todo delete!');
            });
            $div.find('div').on('click', function() {
                console.log('row clicked!');
            });
            $div.find('select').on('change', function () {
                console.log('');
            });

        });


    </script>

    </script>
{% endblock %}

templates/budget/pdf.html.twig
<style>
    .text-red{
        color: red;
    }
    .text-blue{
        color: blue;
    }
</style>

<page backtop="25mm" backleft="13mm" backbottom="15mm" backright="18mm">
    <page_header>
        <img src='images/image-back.jpg'  style='width: 180px; float: right;' alt='Logo' title='Logo'>
    </page_header>
    <page_footer>
        <h5 class="text-red">{{ actualDate | date('d-m-Y H:i:s') }}</h5>
    </page_footer>

    <h1 class="text-blue">Presupuesto {{ presupuesto.nroBudget }}</h1>
    <table>
        <thead>
        <tr>

            <th>Nombre</th>
            <th>Email</th>
            <th>Cuit</th>
{#            <th>Estado</th>#}
        </tr>
        <tr>
            <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>

            <tr>
                <td>{{ presupuesto.cliente.razonSocial }}</td>
                <td>{{ presupuesto.cliente.emial }}</td>
                <td>{{ presupuesto.cliente.cuit }}</td>
            </tr>
            <tr>
                <td colspan="3">
                    {{ presupuesto.cliente.address }}
                </td>
            </tr>

        </tbody>
    </table>
</page>

templates/budget/show.html.twig
{% extends "admin/bars.html.twig" %}

{% block title %}Presupuesto Ver{% endblock %}

{% block contenpage %}
    <h1>Presupuesto Ver</h1>

    <table class="table">
        <tbody>
        {% if(is_granted('ROLE_SUPERVISOR_VENTAS')) %}
            <tr>
                <th>Id</th>
                <td>{{ budget.id }}</td>
            </tr>
        {% endif %}
            <tr>
                <th>Aclaraciones</th>
                <td>{{ budget.aclaraciones }}</td>
            </tr>
            <tr>
                <th>Cliente confirma</th>
                <td>{{ budget.clienteConfirma }}</td>
            </tr>
            <tr>
                <th>Total</th>
                <td>{{ budget.total }}</td>
            </tr>
            <tr>
                <th>Nro presupuesto</th>
                <td>{{ budget.nroBudget }}</td>
            </tr>
            <tr>
                <th>
                    Productos
                </th>
                <td>
                    {% for producto in budget.productos %}
                        {{ producto.title }}
                    {% endfor %}
                </td>
            </tr>
{#            <tr>#}
{#                <th>Creado</th>#}
{#                <td>{{ budget.createdAt ? budget.createdAt|date('d-m-Y H:i:s') : '' }}</td>#}
{#            </tr>#}
            <tr>
                <th>Iniciado</th>
                <td>{{ budget.updatedAt ? budget.updatedAt|date('d-m-Y H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>
    {% if(is_granted('ROLE_SUPERVISOR_VENTAS')) %}
    <a href="{{ path('app_budget_index') }}">Listado</a>


    <a href="{{ path('app_budget_edit', {'id': budget.id}) }}">Editar</a>
    {% endif %}

    <a href="{{ path('app_budget_get_pdf', {'budget': budget.id}) }}">Descargar PDF</a>

{#    {{ include('budget/_delete_form.html.twig') }}#}
{% endblock %}